### ISSUE TITLE
Cannot convert the value "21-08-2023 04:00" to type "System.DateTime

### ISSUE THREAD

**Issue by ndcc5** [Dumraden/SmeshLogParser#1]
Get-Date: The Date parameter cannot be bound. Cannot convert the value "21-08-2023 04:00" to type "System.DateTime". Error: "The string was not recognized as a valid DateTime."
Location C:\Smesh\SmeshLogParser1.3-208.ps1:107 Characters: 27
+     $ProofSub = (Get-Date $poetRoundEnd).AddHours(11)
+ ~~~~~~~~~~~~~
+ CategoryInfo: InvalidArgument: (:) [Get - Date], ParameterBindingException
+ FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.GetDateCommand

You cannot call methods on nulL-valued expressions.
Location C:\Smesh\SmeshLogParser1.3-208.ps1:108 Characters: 5
+     $ProofSubFormatted = $ProofSub.ToString("dd-MM-yyyy HH:mm")
+ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
+ CategoryInfo: InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by Dumraden** [comment]
This is because your node has not gone through submitting a proof, hence it doesn't have a "date" registered in the logs. Once it goes through a single PoET cycle gap, the error will go away and it will start capturing the correct date/time.
